---
- hosts: all
  become: yes
  tasks:
  - name: i want to install a apache2 webserver in debian node
    apt:
      name: apache2
      state: present
    
  - name: i want to start webserver on debian node
    service:
      name: apache2
      state: started

